export const Photos = [
    { src: "./01.jpeg", title: 4, description: 3 },
    { src: "./02.jpeg", title: 1, description: 1 },
    { src: "./03.jpeg", title: 3, description: 4 },
    { src: "./04.jpeg", title: 3, description: 4 },
    { src: "./05.jpeg", title: 3, height: 4 },
    { src: "./07.jpeg", title: 3, height: 4 },
    { src: "./08.jpeg", title: 4, height: 3 },
    { src: "./09.jpeg", title: 4, height: 3 },
    { src: "./10.jpeg", title: 4, height: 3 },
    { src: "./11.jpeg", title: 3, height: 4 }
    // { src: "./12.jpeg", width: 4, height: 3 },
    // { src: "./13.jpeg", width: 4, height: 3 },
    // { src: "./14.jpeg", width: 4, height: 3 },
    // { src: "./15.jpeg", width: 3, height: 4 },
    // { src: "./16.jpeg", width: 4, height: 3 },
    // { src: "./17.jpeg", width: 4, height: 3 },
    // { src: "./18.jpeg", width: 4, height: 3 },
    // { src: "./19.jpeg", width: 3, height: 4 },
    // { src: "./20.jpeg", width: 4, height: 3 },
    // { src: "./21.jpeg", width: 4, height: 3 },
    // { src: "./22.jpeg", width: 4, height: 3 },
    // { src: "./23.jpeg", width: 3, height: 4 },
    // { src: "./24.jpeg", width: 4, height: 3 },
    // { src: "./25.jpeg", width: 4, height: 3 },
    // { src: "./26.jpeg", width: 3, height: 4 },
    // { src: "./27.jpeg", width: 4, height: 3 },
    // { src: "./28.jpeg", width: 3, height: 4 },
    // { src: "./29.jpeg", width: 4, height: 3 },
    // { src: "./30.jpeg", width: 3, height: 4 },
    // { src: "./31.jpeg", width: 4, height: 3 }
];
